# build.yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - non_constant_identifier_names
            - avoid_single_cascade_in_expression_statements
            - avoid_positional_boolean_parameters
