name: bible
description: Tecarta Bible
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animations: ^1.1.2
  bloc: ^6.1.0
  cached_network_image: ^2.3.3
  collection: ^1.14.12
  combos: ^1.2.0
  cupertino_icons: ^1.0.1+1
  equatable: ^1.2.5
  feather_icons_flutter: ^4.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.0
  flutter_downloader: ^1.5.1
  flutter_keyboard_visibility: ^4.0.2
  flutter_localizations:
    sdk: flutter
  flutter_sfsymbols: ^1.0.0
  flutter_svg: ^0.19.2+1
  freezed_annotation: ^0.12.0
  google_fonts: ^1.1.1
  i18n_extension: ^1.4.3
  image_picker: ^0.6.7+12
  in_app_purchase: ^0.3.4+15
  json_annotation: ^3.1.1
  path: ^1.7.0
  path_provider: ^1.6.21
  pedantic: ^1.10.0-nullsafety.3
  provider: ^4.3.2+2
  quill_delta: ^2.0.0
  rxdart: ^0.24.1
  scrollable_positioned_list: ^0.1.8
  share: ^0.6.5+3
  string_validator: ^0.1.4
  tec_cache:
    hosted:
      name: tec_cache
      url: http://noah.tecarta.com:8100
    version: ^2.0.1
  tec_env:
    hosted:
      name: tec_env
      url: http://noah.tecarta.com:8100
    version: ^1.0.1
  tec_html:
    hosted:
      name: tec_html
      url: http://noah.tecarta.com:8100
    version: ^3.1.5
  tec_native_ad:
    hosted:
      name: tec_native_ad
      url: http://noah.tecarta.com:8100
    version: ^0.0.5
  tec_notifications:
    hosted:
      name: tec_notifications
      url: http://noah.tecarta.com:8100
    version: ^0.0.1
  tec_platform_util:
    hosted:
      name: tec_platform_util
      url: http://noah.tecarta.com:8100
    version: ^1.0.2
  tec_user_account:
    hosted:
      name: tec_user_account
      url: http://noah.tecarta.com:8100
    version: ^2.0.18
  tec_util:
    hosted:
      name: tec_util
      url: http://noah.tecarta.com:8100
    version: ^1.2.28
  tec_views:
    # path: ../shared/tec_views
    hosted:
      name: tec_views
      url: http://noah.tecarta.com:8100
    version: ^1.0.8
  tec_volumes:
    hosted:
      name: tec_volumes
      url: http://noah.tecarta.com:8100
    version: ^1.2.16
  tec_web_view:
    hosted:
      name: tec_web_view
      url: http://noah.tecarta.com:8100
    version: ^1.0.0
  tec_widgets:
    hosted:
      name: tec_widgets
      url: http://noah.tecarta.com:8100
    version: ^2.0.23
  tuple: ^1.0.3
  url_launcher: ^5.7.5
  video_player: ^1.0.1
  zefyr: ^1.0.0-dev.2.0

# dependency_overrides:
#   tec_user_account:
#     path: ../shared/tec_user_account

dev_dependencies:
  bloc_test: ^7.1.0
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter
  freezed: ^0.12.3
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

  fonts:
    - family: Open Dyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          style: italic
          weight: 700
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf

  assets:
    - assets/9.sqlite
    - assets/9.zip
    - assets/fonts.json
    - assets/footnote.svg
    - assets/marginNote.svg
    - assets/products.json
    - assets/images/photo0.jpg
    - assets/images/photo1.jpg
    - assets/images/photo2.jpg
    - assets/images/photo3.jpg
    - assets/images/photo4.jpg
    - assets/images/photoBible.jpg
    - assets/images/viewOpLight.mp4
    - assets/images/viewOpDark.mp4
    - assets/images/moveViewLight.mp4
    - assets/images/moveViewDark.mp4
