name: bible
description: Tecarta Bible
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  bloc: ^6.1.0
  cached_network_image: ^3.0.0-nullsafety
  collection: ^1.14.12
  combos: ^1.2.0
  cupertino_icons: ^1.0.0
  equatable: ^2.0.0
  feather_icons_flutter: ^4.7.4
  feature_discovery:
    git:
      url: https://github.com/tecarta/feature_discovery
      ref: a78ecca2eaae2e1e2bf13508f79d220e7d36e1b8
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.0
  flutter_downloader: ^1.5.1
  flutter_keyboard_visibility: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_sfsymbols: ^2.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  freezed_annotation: ^0.14.1
  google_fonts: ^2.0.0-nullsafety.0
  i18n_extension: ^4.0.0
  image_picker: ^0.7.0
  in_app_purchase: ^0.5.0
  json_annotation: ^4.0.0
  native_pdf_renderer: ^3.0.0
  path: ^1.7.0
  path_provider: ^2.0.0-nullsafety
  pedantic: ^1.9.2
  provider: ^4.3.2+2
  quill_delta: ^2.0.0
  scrollable_positioned_list: ^0.1.8
  share: ^2.0.0
  string_validator: ^0.3.0

  tec_cache:
    hosted:
      name: tec_cache
      url: http://noah.tecarta.com:8100
    version: ^2.0.1
  tec_env:
    hosted:
      name: tec_env
      url: http://noah.tecarta.com:8100
    version: ^1.0.1
  tec_html:
    hosted:
      name: tec_html
      url: http://noah.tecarta.com:8100
    version: ^3.3.1
  tec_native_ad:
    hosted:
      name: tec_native_ad
      url: http://noah.tecarta.com:8100
    version: ^1.0.0
  tec_notifications:
    hosted:
      name: tec_notifications
      url: http://noah.tecarta.com:8100
    version: ^0.1.2
  tec_platform_util:
    hosted:
      name: tec_platform_util
      url: http://noah.tecarta.com:8100
    version: ^1.0.2
  tec_selectable:
    hosted:
      name: tec_selectable
      url: http://noah.tecarta.com:8100
    version: ^2.1.5
  tec_user_account:
    hosted:
      name: tec_user_account
      url: http://noah.tecarta.com:8100
    version: ^2.2.3
  tec_util:
    hosted:
      name: tec_util
      url: http://noah.tecarta.com:8100
    version: ^1.3.2
  tec_views:
    hosted:
      name: tec_views
      url: http://noah.tecarta.com:8100
    version: ^1.0.16
  tec_volumes:
    hosted:
      name: tec_volumes
      url: http://noah.tecarta.com:8100
    version: ^1.3.0
  tec_web_view:
    hosted:
      name: tec_web_view
      url: http://noah.tecarta.com:8100
    version: ^1.0.0
  tec_widgets:
    hosted:
      name: tec_widgets
      url: http://noah.tecarta.com:8100
    version: ^2.1.1

  tuple: ^2.0.0
  url_launcher: ^6.0.2
  video_player: ^2.0.2
  zefyr:
    git:
      url: https://github.com/tecarta/zefyr
      path: packages/zefyr
      ref: 00a3c1c952c18e3bb69bf553e3277d70d5069edc

dependency_overrides:
  tec_native_ad:
     path: ../shared/tec_native_ad
  tec_widgets:
    path: ../shared/tec_widgets

dev_dependencies:
  bloc_test: ^7.1.0
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  json_serializable: ^4.0.2

flutter:
  uses-material-design: true

  fonts:
    - family: Open Dyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          style: italic
          weight: 700
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf
    - family: tec_icons
      fonts:
        - asset: assets/fonts/tec_icons.ttf

  assets:
    - assets/9.sqlite
    - assets/9.zip
    - assets/fonts.json
    - assets/footnote.svg
    - assets/marginNote.svg
    - assets/products.json
    - assets/images/photo0.jpg
    - assets/images/photo1.jpg
    - assets/images/photo2.jpg
    - assets/images/photo3.jpg
    - assets/images/photo4.jpg
    - assets/images/photoBible.jpg
#    - assets/images/viewOpLight.mp4
#    - assets/images/viewOpDark.mp4
#    - assets/images/moveViewLight.mp4
#    - assets/images/moveViewDark.mp4
