name: bible
description: Tecarta Bible
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Flutter default dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Localization related dependencies
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^1.4.0

  # External dependencies
  bloc: ^4.0.0
  feather_icons_flutter: ^4.7.4
  flutter_bloc: ^4.0.1
  flutter_local_notifications: ^1.4.4
  freezed_annotation: ^0.11.0
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+2
  json_annotation: ^3.0.1
  provider: ^4.1.3
  rxdart: ^0.24.1
  sliding_sheet: ^0.3.5
  tuple: ^1.0.3

  zefyr:
    git:
      url: git://github.com/memspace/zefyr
      path: packages/zefyr
      commit: 0d69499

  # Internal dependencies
  tec_env:
    hosted:
      name: tec_env
      url: http://noah.tecarta.com:8100
    version: ^1.0.1
  tec_html:
    # path: ../shared/tec_html
    hosted:
      name: tec_html
      url: http://noah.tecarta.com:8100
    version: ^2.0.3
  tec_util:
    hosted:
      name: tec_util
      url: http://noah.tecarta.com:8100
    version: ^1.2.14
  tec_user_account:
    hosted:
      name: tec_user_account
      url: http://noah.tecarta.com:8100
    version: ^1.3.2
  tec_volumes:
    # path: ../shared/tec_volumes
    hosted:
      name: tec_volumes
      url: http://noah.tecarta.com:8100
    version: ^1.0.2
  tec_widgets:
    hosted:
      name: tec_widgets
      url: http://noah.tecarta.com:8100
    version: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^5.1.0
  build_runner: ^1.10.0
  freezed: ^0.11.0
  json_serializable: ^3.3.0
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/0.sqlite
    - assets/0.zip
    - assets/fonts.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
