name: bible
description: Tecarta Bible
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Flutter default dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Localization related dependencies
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^1.4.0

  # External dependencies
  bloc: ^6.0.2
  cached_network_image: ^2.3.1
  combos: ^1.2.0
  equatable: ^1.2.3
  feather_icons_flutter: ^4.7.4
  flutter_bloc: ^6.0.2
  flutter_downloader: ^1.5.0
  flutter_keyboard_visibility: ^3.2.1
  flutter_local_notifications: ^1.4.4
  flutter_svg: ^0.18.0
  freezed_annotation: ^0.11.0+1
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+2
  in_app_purchase: ^0.3.4+3
  json_annotation: ^3.0.1
  path: ^1.7.0
  path_provider: ^1.6.11
  pedantic: ^1.9.2
  permission_handler: ^5.0.1+1
  provider: ^4.1.3
  quill_delta: ^1.0.2
  rxdart: ^0.24.1
  scrollable_positioned_list: ^0.1.7
  share: ^0.6.5
  # sliding_sheet: ^0.3.5
  tuple: ^1.0.3
  url_launcher: ^5.5.1
  zefyr:
    git:
      url: git://github.com/memspace/zefyr
      path: packages/zefyr
      commit: 0d69499

  # Internal dependencies
  sliding_sheet:
    hosted:
      name: sliding_sheet
      url: http://noah.tecarta.com:8100
    version: ^0.3.10
  tec_cache:
    hosted:
      name: tec_cache
      url: http://noah.tecarta.com:8100
    version: ^1.0.0
  tec_env:
    hosted:
      name: tec_env
      url: http://noah.tecarta.com:8100
    version: ^1.0.1
  tec_html:
    hosted:
      name: tec_html
      url: http://noah.tecarta.com:8100
    version: ^3.0.10
  tec_platform_util:
    hosted:
      name: tec_platform_util
      url: http://noah.tecarta.com:8100
    version: ^1.0.0
  tec_util:
    hosted:
      name: tec_util
      url: http://noah.tecarta.com:8100
    version: ^1.2.22
  tec_user_account:
    hosted:
      name: tec_user_account
      url: http://noah.tecarta.com:8100
    version: ^2.0.6
  tec_volumes:
    hosted:
      name: tec_volumes
      url: http://noah.tecarta.com:8100
    version: ^1.1.2
  tec_web_view:
    hosted:
      name: tec_web_view
      url: http://noah.tecarta.com:8100
    version: ^1.0.0
  tec_widgets:
    hosted:
      name: tec_widgets
      url: http://noah.tecarta.com:8100
    version: ^2.0.8

# dependency_overrides:
  # tec_util:
  #   path: ../shared/tec_util
  # tec_widgets:
  #   path: ../shared/tec_widgets
  # sliding_sheet:
  #   path: ../sliding_sheet
  # tec_html:
  #   path: ../shared/tec_html
  # tec_volumes:
  #   path: ../shared/tec_volumes

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^7.0.3
  build_runner: ^1.10.2
  freezed: ^0.11.4
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

  fonts:
    - family: Open Dyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          style: italic
          weight: 700

  assets:
    - assets/0.sqlite
    - assets/0.zip
    - assets/fonts.json
    - assets/footnote.svg
    - assets/marginNote.svg
